version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: abin11/tutortrek_client:latest
    container_name: tutortrek_client
    ports:
      - "3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - connection_network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
          
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: abin11/tutortrek_server:latest
    env_file:
      - ./server/.env
    depends_on:
      - redis
    networks:
      - connection_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - ./.db:/data
    restart: always
    networks:
      - connection_network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
      - client
    ports:
      - "80:80"
    networks:
      - connection_network

networks:
  connection_network:
    driver: bridge